services:
  node_backend:
    container_name: web3
    image: node:20

    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - EXTERNAL_PORT=8080
      - PGDATABASE=web3_0_0_1
      - PGUSER=root
      - PGPASSWORD=root
      - PGHOST=db_psql
    depends_on:
      - db_psql
  db_psql:
    container_name: node_db
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=web3
    volumes:
      - nps_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    depends_on:
      - db_psql

volumes:
  nps_data: {}
